language: node_js

before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile

install: npm install

before_script: greenkeeper-lockfile-update

script: npm run lint

after_script: greenkeeper-lockfile-upload

node_js:
- node
- lts/carbon
- lts/boron
